### ISSUE TITLE
Using `eq` when validating against `const` types is too restrictive

### ISSUE THREAD

**Issue by smaximov** [Malabarba/validate.el#2]
For example, it rejects otherwise valid values of an option which can take values of type `'(const "some string")`. Consider the following snippet:

``` elisp
(defcustom foo "bar"
  "Doc."
  :type '(choice (const "foo")
                 (const "bar")))

(validate-variable 'foo)
```

Evaluating it yields:

```
user-error: Looking for ‘(choice (const "foo") (const "bar"))’ in ‘"bar"’ failed because:
  all of the options failed
    Looking for ‘(const "foo")’ in ‘"bar"’ failed because:
      not the expected value
    Looking for ‘(const "bar")’ in ‘"bar"’ failed because:
      not the expected value
```

I've stumbled upon this while trying to validate [`emmet-self-closing-tab-style`](https://github.com/smihica/emmet-mode/blob/607a23d208405838325ca5203a1900682dad00ac/emmet-mode.el#L210-L227)

**Comment by Malabarba** [comment]
Fair enough. Thanks for the report!
