### ISSUE TITLE
Error with :type choice

### ISSUE THREAD

**Issue by manuel-uberti** [Malabarba/validate.el#6]
I am trying out [dumb-jump](https://github.com/jacktasia/dumb-jump).

As per documentation, I can set these options:
```emacs-lisp
(setq dumb-jump-selector 'ivy
      dumb-jump-prefer-searcher 'rg)
```
If I try using `validate-setq` I get:
```
Error (use-package): dumb-jump :config: Looking for `(choice (const :tag "Popup" popup) (const :tag "Helm" helm) (const :tag "Ivy" other))' in `ivy' failed because:
  all of the options failed
    Looking for `(const :tag "Popup" popup)' in `ivy' failed because:
      not the expected value
    Looking for `(const :tag "Helm" helm)' in `ivy' failed because:
      not the expected value
    Looking for `(const :tag "Ivy" other)' in `ivy' failed because:
      not the expected value
```

**Comment by Malabarba** [comment]
Looks like defcustom is expecting `other`, but you're using `ivy`. Might be a documentation bug in the package, or a bug with the defcustom.

**Comment by manuel-uberti** [comment]
Weird.

@jacktasia what do you think?

**Comment by jacktasia** [comment]
@manuel-uberti Thanks for the heads up. Should be fixed now: https://github.com/jacktasia/dumb-jump/commit/2372300982bab406b80ecfe7209c35ae0388f603 FYI It'll be a few hours before the change gets picked up by MELPA.

**Comment by manuel-uberti** [comment]
@jacktasia thanks, it's working with `validate-setq` now.
